name: Deploy Vanilla JavaScript PWA Checklist App
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint

    - name: Upload logs
      run: |
        mkdir logs
        echo "Logs uploaded on $(date)" > logs/summary.log
        tar -czf logs.tar.gz logs
      continue-on-error: true
